/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AccountRecoveryRouteImport } from './routes/account-recovery'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StatusRouteImport } from './routes/status'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AppPurchaseRouteImport } from './routes/_app._purchase'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppCertificatesRouteImport } from './routes/_app.certificates'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppGradesRouteImport } from './routes/_app.grades'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTranscriptRouteImport } from './routes/_app.transcript'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicAuthRouteImport } from './routes/_public.auth'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicHelpRouteImport } from './routes/_public.help'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicRefundRouteImport } from './routes/_public.refund'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyVerificationCodeRouteImport } from './routes/verify.$verificationCode'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminAiSettingsRouteImport } from './routes/_app.admin.ai-settings'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app.admin.analytics'
import { Route as AppAdminAnnouncementsRouteImport } from './routes/_app.admin.announcements'
import { Route as AppAdminBlogAutoPostRouteImport } from './routes/_app.admin.blog-auto-post'
import { Route as AppAdminContentGeneratorRouteImport } from './routes/_app.admin.content-generator'
import { Route as AppAdminExamEssayRouteImport } from './routes/_app.admin.exam-essay'
import { Route as AppAdminGradebookRouteImport } from './routes/_app.admin.gradebook'
import { Route as AppAdminGradingRouteImport } from './routes/_app.admin.grading'
import { Route as AppAdminMigrationRouteImport } from './routes/_app.admin.migration'
import { Route as AppAdminPlatformSettingsRouteImport } from './routes/_app.admin.platform-settings'
import { Route as AppAdminProjectsRouteImport } from './routes/_app.admin.projects'
import { Route as AppAdminTestimonialsRouteImport } from './routes/_app.admin.testimonials'
import { Route as AppAdminWebhookHealthRouteImport } from './routes/_app.admin.webhook-health'
import { Route as AppWelcomeCourseIdRouteImport } from './routes/_app.welcome.$courseId'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'
import { Route as PublicBlogSlugRouteImport } from './routes/_public.blog.$slug'
import { Route as PublicCoursesIndexRouteImport } from './routes/_public.courses.index'
import { Route as PublicCoursesCourseIdRouteImport } from './routes/_public.courses.$courseId'
import { Route as PublicLegalIndexRouteImport } from './routes/_public.legal.index'
import { Route as PublicLegalSlugRouteImport } from './routes/_public.legal.$slug'
import { Route as AdminMigrationPrintRouteImport } from './routes/admin.migration.print'
import { Route as AppPurchaseCoursesCourseIdFinalEssayRouteImport } from './routes/_app._purchase.courses.$courseId.final-essay'
import { Route as AppPurchaseCoursesCourseIdFinalExamRouteImport } from './routes/_app._purchase.courses.$courseId.final-exam'
import { Route as AppPurchaseCoursesCourseIdProjectRouteImport } from './routes/_app._purchase.courses.$courseId.project'
import { Route as AppPurchaseCoursesCourseIdTextbookRouteImport } from './routes/_app._purchase.courses.$courseId.textbook'
import { Route as AppPurchaseCoursesCourseIdDiscussionsIndexRouteImport } from './routes/_app._purchase.courses.$courseId.discussions.index'
import { Route as AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRouteImport } from './routes/_app._purchase.courses.$courseId.discussions.$discussionId'
import { Route as AppPurchaseCoursesCourseIdLessonsLessonIdRouteImport } from './routes/_app._purchase.courses.$courseId.lessons.$lessonId'
import { Route as AppAdminCoursesCourseIdLessonsLessonIdRouteImport } from './routes/_app.admin.courses.$courseId.lessons.$lessonId'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRecoveryRoute = AccountRecoveryRouteImport.update({
  id: '/account-recovery',
  path: '/account-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPurchaseRoute = AppPurchaseRouteImport.update({
  id: '/_purchase',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTranscriptRoute = AppTranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => AppRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHelpRoute = PublicHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRefundRoute = PublicRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyVerificationCodeRoute = VerifyVerificationCodeRouteImport.update({
  id: '/verify/$verificationCode',
  path: '/verify/$verificationCode',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAiSettingsRoute = AppAdminAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnnouncementsRoute = AppAdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBlogAutoPostRoute = AppAdminBlogAutoPostRouteImport.update({
  id: '/blog-auto-post',
  path: '/blog-auto-post',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminContentGeneratorRoute =
  AppAdminContentGeneratorRouteImport.update({
    id: '/content-generator',
    path: '/content-generator',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminExamEssayRoute = AppAdminExamEssayRouteImport.update({
  id: '/exam-essay',
  path: '/exam-essay',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGradebookRoute = AppAdminGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGradingRoute = AppAdminGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMigrationRoute = AppAdminMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPlatformSettingsRoute =
  AppAdminPlatformSettingsRouteImport.update({
    id: '/platform-settings',
    path: '/platform-settings',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminProjectsRoute = AppAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTestimonialsRoute = AppAdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminWebhookHealthRoute = AppAdminWebhookHealthRouteImport.update({
  id: '/webhook-health',
  path: '/webhook-health',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppWelcomeCourseIdRoute = AppWelcomeCourseIdRouteImport.update({
  id: '/welcome/$courseId',
  path: '/welcome/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesIndexRoute = PublicCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesCourseIdRoute = PublicCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalIndexRoute = PublicLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalSlugRoute = PublicLegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminMigrationPrintRoute = AdminMigrationPrintRouteImport.update({
  id: '/admin/migration/print',
  path: '/admin/migration/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPurchaseCoursesCourseIdFinalEssayRoute =
  AppPurchaseCoursesCourseIdFinalEssayRouteImport.update({
    id: '/courses/$courseId/final-essay',
    path: '/courses/$courseId/final-essay',
    getParentRoute: () => AppPurchaseRoute,
  } as any)
const AppPurchaseCoursesCourseIdFinalExamRoute =
  AppPurchaseCoursesCourseIdFinalExamRouteImport.update({
    id: '/courses/$courseId/final-exam',
    path: '/courses/$courseId/final-exam',
    getParentRoute: () => AppPurchaseRoute,
  } as any)
const AppPurchaseCoursesCourseIdProjectRoute =
  AppPurchaseCoursesCourseIdProjectRouteImport.update({
    id: '/courses/$courseId/project',
    path: '/courses/$courseId/project',
    getParentRoute: () => AppPurchaseRoute,
  } as any)
const AppPurchaseCoursesCourseIdTextbookRoute =
  AppPurchaseCoursesCourseIdTextbookRouteImport.update({
    id: '/courses/$courseId/textbook',
    path: '/courses/$courseId/textbook',
    getParentRoute: () => AppPurchaseRoute,
  } as any)
const AppPurchaseCoursesCourseIdDiscussionsIndexRoute =
  AppPurchaseCoursesCourseIdDiscussionsIndexRouteImport.update({
    id: '/courses/$courseId/discussions/',
    path: '/courses/$courseId/discussions/',
    getParentRoute: () => AppPurchaseRoute,
  } as any)
const AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRoute =
  AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRouteImport.update({
    id: '/courses/$courseId/discussions/$discussionId',
    path: '/courses/$courseId/discussions/$discussionId',
    getParentRoute: () => AppPurchaseRoute,
  } as any)
const AppPurchaseCoursesCourseIdLessonsLessonIdRoute =
  AppPurchaseCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/courses/$courseId/lessons/$lessonId',
    path: '/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => AppPurchaseRoute,
  } as any)
const AppAdminCoursesCourseIdLessonsLessonIdRoute =
  AppAdminCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/courses/$courseId/lessons/$lessonId',
    path: '/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => AppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/account-recovery': typeof AccountRecoveryRoute
  '/index': typeof Char91indexChar93Route
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/billing': typeof AppBillingRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/grades': typeof AppGradesRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/transcript': typeof AppTranscriptRoute
  '/about': typeof PublicAboutRoute
  '/auth': typeof PublicAuthRoute
  '/contact': typeof PublicContactRoute
  '/help': typeof PublicHelpRoute
  '/privacy': typeof PublicPrivacyRoute
  '/refund': typeof PublicRefundRoute
  '/terms': typeof PublicTermsRoute
  '/verify/$verificationCode': typeof VerifyVerificationCodeRoute
  '/verify/': typeof VerifyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/ai-settings': typeof AppAdminAiSettingsRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/announcements': typeof AppAdminAnnouncementsRoute
  '/admin/blog-auto-post': typeof AppAdminBlogAutoPostRoute
  '/admin/content-generator': typeof AppAdminContentGeneratorRoute
  '/admin/exam-essay': typeof AppAdminExamEssayRoute
  '/admin/gradebook': typeof AppAdminGradebookRoute
  '/admin/grading': typeof AppAdminGradingRoute
  '/admin/migration': typeof AppAdminMigrationRoute
  '/admin/platform-settings': typeof AppAdminPlatformSettingsRoute
  '/admin/projects': typeof AppAdminProjectsRoute
  '/admin/testimonials': typeof AppAdminTestimonialsRoute
  '/admin/webhook-health': typeof AppAdminWebhookHealthRoute
  '/welcome/$courseId': typeof AppWelcomeCourseIdRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/courses/$courseId': typeof PublicCoursesCourseIdRoute
  '/legal/$slug': typeof PublicLegalSlugRoute
  '/admin/migration/print': typeof AdminMigrationPrintRoute
  '/admin/': typeof AppAdminIndexRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/courses/': typeof PublicCoursesIndexRoute
  '/legal/': typeof PublicLegalIndexRoute
  '/courses/$courseId/final-essay': typeof AppPurchaseCoursesCourseIdFinalEssayRoute
  '/courses/$courseId/final-exam': typeof AppPurchaseCoursesCourseIdFinalExamRoute
  '/courses/$courseId/project': typeof AppPurchaseCoursesCourseIdProjectRoute
  '/courses/$courseId/textbook': typeof AppPurchaseCoursesCourseIdTextbookRoute
  '/courses/$courseId/discussions/$discussionId': typeof AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRoute
  '/courses/$courseId/lessons/$lessonId': typeof AppPurchaseCoursesCourseIdLessonsLessonIdRoute
  '/admin/courses/$courseId/lessons/$lessonId': typeof AppAdminCoursesCourseIdLessonsLessonIdRoute
  '/courses/$courseId/discussions/': typeof AppPurchaseCoursesCourseIdDiscussionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/account-recovery': typeof AccountRecoveryRoute
  '/index': typeof Char91indexChar93Route
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing': typeof AppBillingRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/grades': typeof AppGradesRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/transcript': typeof AppTranscriptRoute
  '/about': typeof PublicAboutRoute
  '/auth': typeof PublicAuthRoute
  '/contact': typeof PublicContactRoute
  '/help': typeof PublicHelpRoute
  '/privacy': typeof PublicPrivacyRoute
  '/refund': typeof PublicRefundRoute
  '/terms': typeof PublicTermsRoute
  '/verify/$verificationCode': typeof VerifyVerificationCodeRoute
  '/verify': typeof VerifyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/ai-settings': typeof AppAdminAiSettingsRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/announcements': typeof AppAdminAnnouncementsRoute
  '/admin/blog-auto-post': typeof AppAdminBlogAutoPostRoute
  '/admin/content-generator': typeof AppAdminContentGeneratorRoute
  '/admin/exam-essay': typeof AppAdminExamEssayRoute
  '/admin/gradebook': typeof AppAdminGradebookRoute
  '/admin/grading': typeof AppAdminGradingRoute
  '/admin/migration': typeof AppAdminMigrationRoute
  '/admin/platform-settings': typeof AppAdminPlatformSettingsRoute
  '/admin/projects': typeof AppAdminProjectsRoute
  '/admin/testimonials': typeof AppAdminTestimonialsRoute
  '/admin/webhook-health': typeof AppAdminWebhookHealthRoute
  '/welcome/$courseId': typeof AppWelcomeCourseIdRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/courses/$courseId': typeof PublicCoursesCourseIdRoute
  '/legal/$slug': typeof PublicLegalSlugRoute
  '/admin/migration/print': typeof AdminMigrationPrintRoute
  '/admin': typeof AppAdminIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/courses': typeof PublicCoursesIndexRoute
  '/legal': typeof PublicLegalIndexRoute
  '/courses/$courseId/final-essay': typeof AppPurchaseCoursesCourseIdFinalEssayRoute
  '/courses/$courseId/final-exam': typeof AppPurchaseCoursesCourseIdFinalExamRoute
  '/courses/$courseId/project': typeof AppPurchaseCoursesCourseIdProjectRoute
  '/courses/$courseId/textbook': typeof AppPurchaseCoursesCourseIdTextbookRoute
  '/courses/$courseId/discussions/$discussionId': typeof AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRoute
  '/courses/$courseId/lessons/$lessonId': typeof AppPurchaseCoursesCourseIdLessonsLessonIdRoute
  '/admin/courses/$courseId/lessons/$lessonId': typeof AppAdminCoursesCourseIdLessonsLessonIdRoute
  '/courses/$courseId/discussions': typeof AppPurchaseCoursesCourseIdDiscussionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/account-recovery': typeof AccountRecoveryRoute
  '/index': typeof Char91indexChar93Route
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/_purchase': typeof AppPurchaseRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/billing': typeof AppBillingRoute
  '/_app/certificates': typeof AppCertificatesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/grades': typeof AppGradesRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transcript': typeof AppTranscriptRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/auth': typeof PublicAuthRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/help': typeof PublicHelpRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/refund': typeof PublicRefundRoute
  '/_public/terms': typeof PublicTermsRoute
  '/verify/$verificationCode': typeof VerifyVerificationCodeRoute
  '/_public/': typeof PublicIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_app/admin/ai-settings': typeof AppAdminAiSettingsRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/announcements': typeof AppAdminAnnouncementsRoute
  '/_app/admin/blog-auto-post': typeof AppAdminBlogAutoPostRoute
  '/_app/admin/content-generator': typeof AppAdminContentGeneratorRoute
  '/_app/admin/exam-essay': typeof AppAdminExamEssayRoute
  '/_app/admin/gradebook': typeof AppAdminGradebookRoute
  '/_app/admin/grading': typeof AppAdminGradingRoute
  '/_app/admin/migration': typeof AppAdminMigrationRoute
  '/_app/admin/platform-settings': typeof AppAdminPlatformSettingsRoute
  '/_app/admin/projects': typeof AppAdminProjectsRoute
  '/_app/admin/testimonials': typeof AppAdminTestimonialsRoute
  '/_app/admin/webhook-health': typeof AppAdminWebhookHealthRoute
  '/_app/welcome/$courseId': typeof AppWelcomeCourseIdRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/courses/$courseId': typeof PublicCoursesCourseIdRoute
  '/_public/legal/$slug': typeof PublicLegalSlugRoute
  '/admin/migration/print': typeof AdminMigrationPrintRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/courses/': typeof PublicCoursesIndexRoute
  '/_public/legal/': typeof PublicLegalIndexRoute
  '/_app/_purchase/courses/$courseId/final-essay': typeof AppPurchaseCoursesCourseIdFinalEssayRoute
  '/_app/_purchase/courses/$courseId/final-exam': typeof AppPurchaseCoursesCourseIdFinalExamRoute
  '/_app/_purchase/courses/$courseId/project': typeof AppPurchaseCoursesCourseIdProjectRoute
  '/_app/_purchase/courses/$courseId/textbook': typeof AppPurchaseCoursesCourseIdTextbookRoute
  '/_app/_purchase/courses/$courseId/discussions/$discussionId': typeof AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRoute
  '/_app/_purchase/courses/$courseId/lessons/$lessonId': typeof AppPurchaseCoursesCourseIdLessonsLessonIdRoute
  '/_app/admin/courses/$courseId/lessons/$lessonId': typeof AppAdminCoursesCourseIdLessonsLessonIdRoute
  '/_app/_purchase/courses/$courseId/discussions/': typeof AppPurchaseCoursesCourseIdDiscussionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-recovery'
    | '/index'
    | '/onboarding'
    | '/reset-password'
    | '/status'
    | '/unsubscribe'
    | '/admin'
    | '/billing'
    | '/certificates'
    | '/dashboard'
    | '/grades'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/transcript'
    | '/about'
    | '/auth'
    | '/contact'
    | '/help'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/verify/$verificationCode'
    | '/verify/'
    | '/.lovable/oauth/consent'
    | '/admin/ai-settings'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/blog-auto-post'
    | '/admin/content-generator'
    | '/admin/exam-essay'
    | '/admin/gradebook'
    | '/admin/grading'
    | '/admin/migration'
    | '/admin/platform-settings'
    | '/admin/projects'
    | '/admin/testimonials'
    | '/admin/webhook-health'
    | '/welcome/$courseId'
    | '/blog/$slug'
    | '/courses/$courseId'
    | '/legal/$slug'
    | '/admin/migration/print'
    | '/admin/'
    | '/blog/'
    | '/courses/'
    | '/legal/'
    | '/courses/$courseId/final-essay'
    | '/courses/$courseId/final-exam'
    | '/courses/$courseId/project'
    | '/courses/$courseId/textbook'
    | '/courses/$courseId/discussions/$discussionId'
    | '/courses/$courseId/lessons/$lessonId'
    | '/admin/courses/$courseId/lessons/$lessonId'
    | '/courses/$courseId/discussions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-recovery'
    | '/index'
    | '/onboarding'
    | '/reset-password'
    | '/status'
    | '/unsubscribe'
    | '/billing'
    | '/certificates'
    | '/dashboard'
    | '/grades'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/transcript'
    | '/about'
    | '/auth'
    | '/contact'
    | '/help'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/verify/$verificationCode'
    | '/verify'
    | '/.lovable/oauth/consent'
    | '/admin/ai-settings'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/blog-auto-post'
    | '/admin/content-generator'
    | '/admin/exam-essay'
    | '/admin/gradebook'
    | '/admin/grading'
    | '/admin/migration'
    | '/admin/platform-settings'
    | '/admin/projects'
    | '/admin/testimonials'
    | '/admin/webhook-health'
    | '/welcome/$courseId'
    | '/blog/$slug'
    | '/courses/$courseId'
    | '/legal/$slug'
    | '/admin/migration/print'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/legal'
    | '/courses/$courseId/final-essay'
    | '/courses/$courseId/final-exam'
    | '/courses/$courseId/project'
    | '/courses/$courseId/textbook'
    | '/courses/$courseId/discussions/$discussionId'
    | '/courses/$courseId/lessons/$lessonId'
    | '/admin/courses/$courseId/lessons/$lessonId'
    | '/courses/$courseId/discussions'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/account-recovery'
    | '/index'
    | '/onboarding'
    | '/reset-password'
    | '/status'
    | '/unsubscribe'
    | '/_app/_purchase'
    | '/_app/admin'
    | '/_app/billing'
    | '/_app/certificates'
    | '/_app/dashboard'
    | '/_app/grades'
    | '/_app/leaderboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/transcript'
    | '/_public/about'
    | '/_public/auth'
    | '/_public/contact'
    | '/_public/help'
    | '/_public/privacy'
    | '/_public/refund'
    | '/_public/terms'
    | '/verify/$verificationCode'
    | '/_public/'
    | '/verify/'
    | '/.lovable/oauth/consent'
    | '/_app/admin/ai-settings'
    | '/_app/admin/analytics'
    | '/_app/admin/announcements'
    | '/_app/admin/blog-auto-post'
    | '/_app/admin/content-generator'
    | '/_app/admin/exam-essay'
    | '/_app/admin/gradebook'
    | '/_app/admin/grading'
    | '/_app/admin/migration'
    | '/_app/admin/platform-settings'
    | '/_app/admin/projects'
    | '/_app/admin/testimonials'
    | '/_app/admin/webhook-health'
    | '/_app/welcome/$courseId'
    | '/_public/blog/$slug'
    | '/_public/courses/$courseId'
    | '/_public/legal/$slug'
    | '/admin/migration/print'
    | '/_app/admin/'
    | '/_public/blog/'
    | '/_public/courses/'
    | '/_public/legal/'
    | '/_app/_purchase/courses/$courseId/final-essay'
    | '/_app/_purchase/courses/$courseId/final-exam'
    | '/_app/_purchase/courses/$courseId/project'
    | '/_app/_purchase/courses/$courseId/textbook'
    | '/_app/_purchase/courses/$courseId/discussions/$discussionId'
    | '/_app/_purchase/courses/$courseId/lessons/$lessonId'
    | '/_app/admin/courses/$courseId/lessons/$lessonId'
    | '/_app/_purchase/courses/$courseId/discussions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AccountRecoveryRoute: typeof AccountRecoveryRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatusRoute: typeof StatusRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyVerificationCodeRoute: typeof VerifyVerificationCodeRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  AdminMigrationPrintRoute: typeof AdminMigrationPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-recovery': {
      id: '/account-recovery'
      path: '/account-recovery'
      fullPath: '/account-recovery'
      preLoaderRoute: typeof AccountRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_purchase': {
      id: '/_app/_purchase'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPurchaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates': {
      id: '/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grades': {
      id: '/_app/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transcript': {
      id: '/_app/transcript'
      path: '/transcript'
      fullPath: '/transcript'
      preLoaderRoute: typeof AppTranscriptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/help': {
      id: '/_public/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof PublicHelpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/refund': {
      id: '/_public/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof PublicRefundRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$verificationCode': {
      id: '/verify/$verificationCode'
      path: '/verify/$verificationCode'
      fullPath: '/verify/$verificationCode'
      preLoaderRoute: typeof VerifyVerificationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ai-settings': {
      id: '/_app/admin/ai-settings'
      path: '/ai-settings'
      fullPath: '/admin/ai-settings'
      preLoaderRoute: typeof AppAdminAiSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/announcements': {
      id: '/_app/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AppAdminAnnouncementsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/blog-auto-post': {
      id: '/_app/admin/blog-auto-post'
      path: '/blog-auto-post'
      fullPath: '/admin/blog-auto-post'
      preLoaderRoute: typeof AppAdminBlogAutoPostRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/content-generator': {
      id: '/_app/admin/content-generator'
      path: '/content-generator'
      fullPath: '/admin/content-generator'
      preLoaderRoute: typeof AppAdminContentGeneratorRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/exam-essay': {
      id: '/_app/admin/exam-essay'
      path: '/exam-essay'
      fullPath: '/admin/exam-essay'
      preLoaderRoute: typeof AppAdminExamEssayRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/gradebook': {
      id: '/_app/admin/gradebook'
      path: '/gradebook'
      fullPath: '/admin/gradebook'
      preLoaderRoute: typeof AppAdminGradebookRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/grading': {
      id: '/_app/admin/grading'
      path: '/grading'
      fullPath: '/admin/grading'
      preLoaderRoute: typeof AppAdminGradingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/migration': {
      id: '/_app/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AppAdminMigrationRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/platform-settings': {
      id: '/_app/admin/platform-settings'
      path: '/platform-settings'
      fullPath: '/admin/platform-settings'
      preLoaderRoute: typeof AppAdminPlatformSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/projects': {
      id: '/_app/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AppAdminProjectsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/testimonials': {
      id: '/_app/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AppAdminTestimonialsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/webhook-health': {
      id: '/_app/admin/webhook-health'
      path: '/webhook-health'
      fullPath: '/admin/webhook-health'
      preLoaderRoute: typeof AppAdminWebhookHealthRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/welcome/$courseId': {
      id: '/_app/welcome/$courseId'
      path: '/welcome/$courseId'
      fullPath: '/welcome/$courseId'
      preLoaderRoute: typeof AppWelcomeCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses/': {
      id: '/_public/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof PublicCoursesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses/$courseId': {
      id: '/_public/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof PublicCoursesCourseIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/': {
      id: '/_public/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof PublicLegalIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/$slug': {
      id: '/_public/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof PublicLegalSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/migration/print': {
      id: '/admin/migration/print'
      path: '/admin/migration/print'
      fullPath: '/admin/migration/print'
      preLoaderRoute: typeof AdminMigrationPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_purchase/courses/$courseId/final-essay': {
      id: '/_app/_purchase/courses/$courseId/final-essay'
      path: '/courses/$courseId/final-essay'
      fullPath: '/courses/$courseId/final-essay'
      preLoaderRoute: typeof AppPurchaseCoursesCourseIdFinalEssayRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/_purchase/courses/$courseId/final-exam': {
      id: '/_app/_purchase/courses/$courseId/final-exam'
      path: '/courses/$courseId/final-exam'
      fullPath: '/courses/$courseId/final-exam'
      preLoaderRoute: typeof AppPurchaseCoursesCourseIdFinalExamRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/_purchase/courses/$courseId/project': {
      id: '/_app/_purchase/courses/$courseId/project'
      path: '/courses/$courseId/project'
      fullPath: '/courses/$courseId/project'
      preLoaderRoute: typeof AppPurchaseCoursesCourseIdProjectRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/_purchase/courses/$courseId/textbook': {
      id: '/_app/_purchase/courses/$courseId/textbook'
      path: '/courses/$courseId/textbook'
      fullPath: '/courses/$courseId/textbook'
      preLoaderRoute: typeof AppPurchaseCoursesCourseIdTextbookRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/_purchase/courses/$courseId/discussions/': {
      id: '/_app/_purchase/courses/$courseId/discussions/'
      path: '/courses/$courseId/discussions'
      fullPath: '/courses/$courseId/discussions/'
      preLoaderRoute: typeof AppPurchaseCoursesCourseIdDiscussionsIndexRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/_purchase/courses/$courseId/discussions/$discussionId': {
      id: '/_app/_purchase/courses/$courseId/discussions/$discussionId'
      path: '/courses/$courseId/discussions/$discussionId'
      fullPath: '/courses/$courseId/discussions/$discussionId'
      preLoaderRoute: typeof AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/_purchase/courses/$courseId/lessons/$lessonId': {
      id: '/_app/_purchase/courses/$courseId/lessons/$lessonId'
      path: '/courses/$courseId/lessons/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AppPurchaseCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/admin/courses/$courseId/lessons/$lessonId': {
      id: '/_app/admin/courses/$courseId/lessons/$lessonId'
      path: '/courses/$courseId/lessons/$lessonId'
      fullPath: '/admin/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AppAdminCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppPurchaseRouteChildren {
  AppPurchaseCoursesCourseIdFinalEssayRoute: typeof AppPurchaseCoursesCourseIdFinalEssayRoute
  AppPurchaseCoursesCourseIdFinalExamRoute: typeof AppPurchaseCoursesCourseIdFinalExamRoute
  AppPurchaseCoursesCourseIdProjectRoute: typeof AppPurchaseCoursesCourseIdProjectRoute
  AppPurchaseCoursesCourseIdTextbookRoute: typeof AppPurchaseCoursesCourseIdTextbookRoute
  AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRoute: typeof AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRoute
  AppPurchaseCoursesCourseIdLessonsLessonIdRoute: typeof AppPurchaseCoursesCourseIdLessonsLessonIdRoute
  AppPurchaseCoursesCourseIdDiscussionsIndexRoute: typeof AppPurchaseCoursesCourseIdDiscussionsIndexRoute
}

const AppPurchaseRouteChildren: AppPurchaseRouteChildren = {
  AppPurchaseCoursesCourseIdFinalEssayRoute:
    AppPurchaseCoursesCourseIdFinalEssayRoute,
  AppPurchaseCoursesCourseIdFinalExamRoute:
    AppPurchaseCoursesCourseIdFinalExamRoute,
  AppPurchaseCoursesCourseIdProjectRoute:
    AppPurchaseCoursesCourseIdProjectRoute,
  AppPurchaseCoursesCourseIdTextbookRoute:
    AppPurchaseCoursesCourseIdTextbookRoute,
  AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRoute:
    AppPurchaseCoursesCourseIdDiscussionsDiscussionIdRoute,
  AppPurchaseCoursesCourseIdLessonsLessonIdRoute:
    AppPurchaseCoursesCourseIdLessonsLessonIdRoute,
  AppPurchaseCoursesCourseIdDiscussionsIndexRoute:
    AppPurchaseCoursesCourseIdDiscussionsIndexRoute,
}

const AppPurchaseRouteWithChildren = AppPurchaseRoute._addFileChildren(
  AppPurchaseRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAiSettingsRoute: typeof AppAdminAiSettingsRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminAnnouncementsRoute: typeof AppAdminAnnouncementsRoute
  AppAdminBlogAutoPostRoute: typeof AppAdminBlogAutoPostRoute
  AppAdminContentGeneratorRoute: typeof AppAdminContentGeneratorRoute
  AppAdminExamEssayRoute: typeof AppAdminExamEssayRoute
  AppAdminGradebookRoute: typeof AppAdminGradebookRoute
  AppAdminGradingRoute: typeof AppAdminGradingRoute
  AppAdminMigrationRoute: typeof AppAdminMigrationRoute
  AppAdminPlatformSettingsRoute: typeof AppAdminPlatformSettingsRoute
  AppAdminProjectsRoute: typeof AppAdminProjectsRoute
  AppAdminTestimonialsRoute: typeof AppAdminTestimonialsRoute
  AppAdminWebhookHealthRoute: typeof AppAdminWebhookHealthRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminCoursesCourseIdLessonsLessonIdRoute: typeof AppAdminCoursesCourseIdLessonsLessonIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAiSettingsRoute: AppAdminAiSettingsRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminAnnouncementsRoute: AppAdminAnnouncementsRoute,
  AppAdminBlogAutoPostRoute: AppAdminBlogAutoPostRoute,
  AppAdminContentGeneratorRoute: AppAdminContentGeneratorRoute,
  AppAdminExamEssayRoute: AppAdminExamEssayRoute,
  AppAdminGradebookRoute: AppAdminGradebookRoute,
  AppAdminGradingRoute: AppAdminGradingRoute,
  AppAdminMigrationRoute: AppAdminMigrationRoute,
  AppAdminPlatformSettingsRoute: AppAdminPlatformSettingsRoute,
  AppAdminProjectsRoute: AppAdminProjectsRoute,
  AppAdminTestimonialsRoute: AppAdminTestimonialsRoute,
  AppAdminWebhookHealthRoute: AppAdminWebhookHealthRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminCoursesCourseIdLessonsLessonIdRoute:
    AppAdminCoursesCourseIdLessonsLessonIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppPurchaseRoute: typeof AppPurchaseRouteWithChildren
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBillingRoute: typeof AppBillingRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGradesRoute: typeof AppGradesRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTranscriptRoute: typeof AppTranscriptRoute
  AppWelcomeCourseIdRoute: typeof AppWelcomeCourseIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPurchaseRoute: AppPurchaseRouteWithChildren,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBillingRoute: AppBillingRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGradesRoute: AppGradesRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTranscriptRoute: AppTranscriptRoute,
  AppWelcomeCourseIdRoute: AppWelcomeCourseIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAuthRoute: typeof PublicAuthRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicHelpRoute: typeof PublicHelpRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicRefundRoute: typeof PublicRefundRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicCoursesCourseIdRoute: typeof PublicCoursesCourseIdRoute
  PublicLegalSlugRoute: typeof PublicLegalSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicCoursesIndexRoute: typeof PublicCoursesIndexRoute
  PublicLegalIndexRoute: typeof PublicLegalIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAuthRoute: PublicAuthRoute,
  PublicContactRoute: PublicContactRoute,
  PublicHelpRoute: PublicHelpRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicRefundRoute: PublicRefundRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicCoursesCourseIdRoute: PublicCoursesCourseIdRoute,
  PublicLegalSlugRoute: PublicLegalSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicCoursesIndexRoute: PublicCoursesIndexRoute,
  PublicLegalIndexRoute: PublicLegalIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AccountRecoveryRoute: AccountRecoveryRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatusRoute: StatusRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyVerificationCodeRoute: VerifyVerificationCodeRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  AdminMigrationPrintRoute: AdminMigrationPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
