// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list_my_courses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_courses_default = defineTool({
  name: "list_my_courses",
  title: "List my courses",
  description: "List the SoloSuccess Academy courses the signed-in user has purchased, with completion progress.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: purchases, error: pErr } = await sb.from("purchases").select("course_id, created_at, courses!inner(id, title, subtitle, phase, order_number)").eq("user_id", userId);
    if (pErr) {
      return { content: [{ type: "text", text: pErr.message }], isError: true };
    }
    const courseIds = (purchases ?? []).map((p) => p.course_id);
    let progressByCourse = {};
    if (courseIds.length > 0) {
      const { data: lessons } = await sb.from("lessons").select("id, course_id").in("course_id", courseIds).eq("is_published", true);
      const lessonIds = (lessons ?? []).map((l) => l.id);
      const lessonToCourse = {};
      (lessons ?? []).forEach((l) => {
        lessonToCourse[l.id] = l.course_id;
        progressByCourse[l.course_id] ??= { completed: 0, total: 0 };
        progressByCourse[l.course_id].total += 1;
      });
      if (lessonIds.length > 0) {
        const { data: progress } = await sb.from("user_progress").select("lesson_id, completed").eq("user_id", userId).in("lesson_id", lessonIds);
        (progress ?? []).forEach((row) => {
          if (!row.completed) return;
          const cid = lessonToCourse[row.lesson_id];
          if (cid && progressByCourse[cid]) progressByCourse[cid].completed += 1;
        });
      }
    }
    const items = (purchases ?? []).map((p) => {
      const prog = progressByCourse[p.course_id] ?? { completed: 0, total: 0 };
      return {
        course_id: p.course_id,
        title: p.courses?.title,
        subtitle: p.courses?.subtitle,
        phase: p.courses?.phase,
        order_number: p.courses?.order_number,
        purchased_at: p.created_at,
        lessons_completed: prog.completed,
        lessons_total: prog.total,
        percent_complete: prog.total > 0 ? Math.round(prog.completed / prog.total * 100) : 0
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { courses: items }
    };
  }
});

// src/lib/mcp/tools/get_my_progress.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_progress_default = defineTool2({
  name: "get_my_progress",
  title: "Get my learning progress",
  description: "Get the signed-in user's total XP, current learning streak, longest streak, and profile display name.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const [gamRes, profileRes] = await Promise.all([
      sb.from("user_gamification").select("total_xp, current_streak, longest_streak, last_activity_date").eq("user_id", userId).maybeSingle(),
      sb.from("profiles").select("display_name, full_name").eq("id", userId).maybeSingle()
    ]);
    const summary = {
      user_id: userId,
      email: ctx.getUserEmail?.() ?? null,
      display_name: profileRes.data?.display_name ?? profileRes.data?.full_name ?? null,
      total_xp: gamRes.data?.total_xp ?? 0,
      current_streak_days: gamRes.data?.current_streak ?? 0,
      longest_streak_days: gamRes.data?.longest_streak ?? 0,
      last_activity_date: gamRes.data?.last_activity_date ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list_my_certificates.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_certificates_default = defineTool3({
  name: "list_my_certificates",
  title: "List my certificates",
  description: "List certificates the signed-in user has earned, including course title, issue date, and verification code.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("certificates").select("id, course_id, course_title, student_name, issued_at, verification_code, revoked_at").eq("user_id", ctx.getUserId()).order("issued_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const items = (data ?? []).map((c) => ({
      ...c,
      verify_url: `https://solosuccessacademy.app/verify/${c.verification_code}`,
      status: c.revoked_at ? "revoked" : "valid"
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { certificates: items }
    };
  }
});

// src/lib/mcp/tools/search_lessons.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_lessons_default = defineTool4({
  name: "search_lessons",
  title: "Search my lessons",
  description: "Search published lesson titles and descriptions across the courses the signed-in user has purchased.",
  inputSchema: {
    query: z.string().min(1).describe("Keyword or phrase to search lesson titles and descriptions for."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum results to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const max = limit ?? 20;
    const { data: purchases } = await sb.from("purchases").select("course_id").eq("user_id", ctx.getUserId());
    const courseIds = (purchases ?? []).map((p) => p.course_id);
    if (courseIds.length === 0) {
      return {
        content: [{ type: "text", text: "You have not purchased any courses yet." }],
        structuredContent: { lessons: [] }
      };
    }
    const like = `%${query.replace(/[%_]/g, (m) => `\\${m}`)}%`;
    const { data, error } = await sb.from("lessons").select("id, course_id, title, description, type, order_number, duration_minutes").in("course_id", courseIds).eq("is_published", true).or(`title.ilike.${like},description.ilike.${like}`).order("order_number", { ascending: true }).limit(max);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { lessons: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uiayptizkarnbomkajot";
var mcp_default = defineMcp({
  name: "solosuccess-academy-mcp",
  title: "SoloSuccess Academy",
  version: "0.1.0",
  instructions: "Tools for SoloSuccess Academy students. Use these to look up the signed-in student's purchased courses, progress (XP and streak), earned certificates, and search lesson content within their enrolled courses.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_my_courses_default,
    get_my_progress_default,
    list_my_certificates_default,
    search_lessons_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
